puts 'Borrando toda la base de datos...'

Calificacion.destroy_all
Patrimonio.destroy_all
PatrimonioTipo.destroy_all
Comuna.destroy_all
Prov.destroy_all
Region.destroy_all
User.destroy_all

puts 'OK Base de datos borrada.'
puts 'Creando regiones...'

Region.create([
                { id: 1, nombre: 'Arica y Parinacota', region_ordinal: 'XV' },
                { id: 2, nombre: 'Tarapacá', region_ordinal: 'I' },
                { id: 3, nombre: 'Antofagasta', region_ordinal: 'II' },
                { id: 4, nombre: 'Atacama', region_ordinal: 'III' },
                { id: 5, nombre: 'Coquimbo', region_ordinal: 'IV' },
                { id: 6, nombre: 'Valparaiso', region_ordinal: 'V' },
                { id: 7, nombre: 'Metropolitana de Santiago', region_ordinal: 'RM' },
                { id: 8, nombre: 'Libertador General Bernardo O\'Higgins', region_ordinal: 'VI' },
                { id: 9, nombre: 'Maule', region_ordinal: 'VII' },
                { id: 10, nombre: 'Biobío', region_ordinal: 'VIII' },
                { id: 11, nombre: 'La Araucanía', region_ordinal: 'IX' },
                { id: 12, nombre: 'Los Ríos', region_ordinal: 'XIV' },
                { id: 13, nombre: 'Los Lagos', region_ordinal: 'X' },
                { id: 14, nombre: 'Aisén del General Carlos Ibáñez del Campo', region_ordinal: 'XI' },
                { id: 15, nombre: 'Magallanes y de la Antártica Chilena', region_ordinal: 'XII' }
              ])

puts 'Creando provincias ...'

Prov.create([
              { id: 1, nombre: 'Arica', region_id: 1 },
              { id: 2, nombre: 'Parinacota', region_id: 1 },
              { id: 3, nombre: 'Iquique', region_id: 2 },
              { id: 4, nombre: 'El Tamarugal', region_id: 2 },
              { id: 5, nombre: 'Tocopilla', region_id: 3 },
              { id: 6, nombre: 'El Loa', region_id: 3 },
              { id: 7, nombre: 'Antofagasta', region_id: 3 },
              { id: 8, nombre: 'Chañaral', region_id: 4 },
              { id: 9, nombre: 'Copiapó', region_id: 4 },
              { id: 10, nombre: 'Huasco', region_id: 4 },
              { id: 11, nombre: 'Elqui', region_id: 5 },
              { id: 12, nombre: 'Limarí', region_id: 5 },
              { id: 13, nombre: 'Choapa', region_id: 5 },
              { id: 14, nombre: 'Petorca', region_id: 6 },
              { id: 15, nombre: 'Los Andes', region_id: 6 },
              { id: 16, nombre: 'San Felipe de Aconcagua', region_id: 6 },
              { id: 17, nombre: 'Quillota', region_id: 6 },
              { id: 18, nombre: 'Valparaiso', region_id: 6 },
              { id: 19, nombre: 'San Antonio', region_id: 6 },
              { id: 20, nombre: 'Isla de Pascua', region_id: 6 },
              { id: 21, nombre: 'Marga Marga', region_id: 6 },
              { id: 22, nombre: 'Chacabuco', region_id: 7 },
              { id: 23, nombre: 'Santiago', region_id: 7 },
              { id: 24, nombre: 'Cordillera', region_id: 7 },
              { id: 25, nombre: 'Maipo', region_id: 7 },
              { id: 26, nombre: 'Melipilla', region_id: 7 },
              { id: 27, nombre: 'Talagante', region_id: 7 },
              { id: 28, nombre: 'Cachapoal', region_id: 8 },
              { id: 29, nombre: 'Colchagua', region_id: 8 },
              { id: 30, nombre: 'Cardenal Caro', region_id: 8 },
              { id: 31, nombre: 'Curicó', region_id: 9 },
              { id: 32, nombre: 'Talca', region_id: 9 },
              { id: 33, nombre: 'Linares', region_id: 9 },
              { id: 34, nombre: 'Cauquenes', region_id: 9 },
              { id: 35, nombre: 'Diguillín', region_id: 10 },
              { id: 36, nombre: 'Itata', region_id: 10 },
              { id: 37, nombre: 'Punilla', region_id: 10 },
              { id: 38, nombre: 'Bio Bío', region_id: 11 },
              { id: 39, nombre: 'Concepción', region_id: 11 },
              { id: 40, nombre: 'Arauco', region_id: 11 },
              { id: 41, nombre: 'Malleco', region_id: 12 },
              { id: 42, nombre: 'Cautín', region_id: 12 },
              { id: 43, nombre: 'Valdivia', region_id: 13 },
              { id: 44, nombre: 'Ranco', region_id: 13 },
              { id: 45, nombre: 'Osorno', region_id: 14 },
              { id: 46, nombre: 'Llanquihue', region_id: 14 },
              { id: 47, nombre: 'Chiloé', region_id: 14 },
              { id: 48, nombre: 'Palena', region_id: 14 },
              { id: 49, nombre: 'Coyhaique', region_id: 15 },
              { id: 50, nombre: 'Aysén', region_id: 15 },
              { id: 51, nombre: 'General Carrera', region_id: 15 },
              { id: 52, nombre: 'Capitán Prat', region_id: 15 },
              { id: 53, nombre: 'Última Esperanza', region_id: 16 },
              { id: 54, nombre: 'Magallanes', region_id: 16 },
              { id: 55, nombre: 'Tierra del Fuego', region_id: 16 },
              { id: 56, nombre: 'Antártica Chilena', region_id: 16 }
            ])

puts 'Creando comunas ...'

Comuna.create([
                { id: 1, nombre: 'Arica', prov_id: 1 },
                { id: 2, nombre: 'Camarones', prov_id: 1 },
                { id: 3, nombre: 'General Lagos', prov_id: 2 },
                { id: 4, nombre: 'Putre', prov_id: 2 },
                { id: 5, nombre: 'Alto Hospicio', prov_id: 3 },
                { id: 6, nombre: 'Iquique', prov_id: 3 },
                { id: 7, nombre: 'Camiña', prov_id: 4 },
                { id: 8, nombre: 'Colchane', prov_id: 4 },
                { id: 9, nombre: 'Huara', prov_id: 4 },
                { id: 10, nombre: 'Pica', prov_id: 4 },
                { id: 11, nombre: 'Pozo Almonte', prov_id: 4 },
                { id: 12, nombre: 'Tocopilla', prov_id: 5 },
                { id: 13, nombre: 'María Elena', prov_id: 5 },
                { id: 14, nombre: 'Calama', prov_id: 6 },
                { id: 15, nombre: 'Ollague', prov_id: 6 },
                { id: 16, nombre: 'San Pedro de Atacama', prov_id: 6 },
                { id: 17, nombre: 'Antofagasta', prov_id: 7 },
                { id: 18, nombre: 'Mejillones', prov_id: 7 },
                { id: 19, nombre: 'Sierra Gorda', prov_id: 7 },
                { id: 20, nombre: 'Taltal', prov_id: 7 },
                { id: 21, nombre: 'Chañaral', prov_id: 8 },
                { id: 22, nombre: 'Diego de Almagro', prov_id: 8 },
                { id: 23, nombre: 'Copiapó', prov_id: 9 },
                { id: 24, nombre: 'Caldera', prov_id: 9 },
                { id: 25, nombre: 'Tierra Amarilla', prov_id: 9 },
                { id: 26, nombre: 'Vallenar', prov_id: 10 },
                { id: 27, nombre: 'Alto del Carmen', prov_id: 10 },
                { id: 28, nombre: 'Freirina', prov_id: 10 },
                { id: 29, nombre: 'Huasco', prov_id: 10 },
                { id: 30, nombre: 'La Serena', prov_id: 11 },
                { id: 31, nombre: 'Coquimbo', prov_id: 11 },
                { id: 32, nombre: 'Andacollo', prov_id: 11 },
                { id: 33, nombre: 'La Higuera', prov_id: 11 },
                { id: 34, nombre: 'Paihuano', prov_id: 11 },
                { id: 35, nombre: 'Vicuña', prov_id: 11 },
                { id: 36, nombre: 'Ovalle', prov_id: 12 },
                { id: 37, nombre: 'Combarbalá', prov_id: 12 },
                { id: 38, nombre: 'Monte Patria', prov_id: 12 },
                { id: 39, nombre: 'Punitaqui', prov_id: 12 },
                { id: 40, nombre: 'Río Hurtado', prov_id: 12 },
                { id: 41, nombre: 'Illapel', prov_id: 13 },
                { id: 42, nombre: 'Canela', prov_id: 13 },
                { id: 43, nombre: 'Los Vilos', prov_id: 13 },
                { id: 44, nombre: 'Salamanca', prov_id: 13 },
                { id: 45, nombre: 'La Ligua', prov_id: 14 },
                { id: 46, nombre: 'Cabildo', prov_id: 14 },
                { id: 47, nombre: 'Zapallar', prov_id: 14 },
                { id: 48, nombre: 'Papudo', prov_id: 14 },
                { id: 49, nombre: 'Petorca', prov_id: 14 },
                { id: 50, nombre: 'Los Andes', prov_id: 15 },
                { id: 51, nombre: 'San Esteban', prov_id: 15 },
                { id: 52, nombre: 'Calle Larga', prov_id: 15 },
                { id: 53, nombre: 'Rinconada', prov_id: 15 },
                { id: 54, nombre: 'San Felipe', prov_id: 16 },
                { id: 55, nombre: 'Llaillay', prov_id: 16 },
                { id: 56, nombre: 'Putaendo', prov_id: 16 },
                { id: 57, nombre: 'Santa María', prov_id: 16 },
                { id: 58, nombre: 'Catemu', prov_id: 16 },
                { id: 59, nombre: 'Panquehue', prov_id: 16 },
                { id: 60, nombre: 'Quillota', prov_id: 17 },
                { id: 61, nombre: 'La Cruz', prov_id: 17 },
                { id: 62, nombre: 'La Calera', prov_id: 17 },
                { id: 63, nombre: 'Nogales', prov_id: 17 },
                { id: 64, nombre: 'Hijuelas', prov_id: 17 },
                { id: 65, nombre: 'Valparaíso', prov_id: 18 },
                { id: 66, nombre: 'Viña del Mar', prov_id: 18 },
                { id: 67, nombre: 'Concón', prov_id: 18 },
                { id: 68, nombre: 'Quintero', prov_id: 18 },
                { id: 69, nombre: 'Puchuncaví', prov_id: 18 },
                { id: 70, nombre: 'Casablanca', prov_id: 18 },
                { id: 71, nombre: 'Juan Fernández', prov_id: 18 },
                { id: 72, nombre: 'San Antonio', prov_id: 19 },
                { id: 73, nombre: 'Cartagena', prov_id: 19 },
                { id: 74, nombre: 'El Tabo', prov_id: 19 },
                { id: 75, nombre: 'El Quisco', prov_id: 19 },
                { id: 76, nombre: 'Algarrobo', prov_id: 19 },
                { id: 77, nombre: 'Santo Domingo', prov_id: 19 },
                { id: 78, nombre: 'Isla de Pascua', prov_id: 20 },
                { id: 79, nombre: 'Quilpué', prov_id: 21 },
                { id: 80, nombre: 'Limache', prov_id: 21 },
                { id: 81, nombre: 'Olmué', prov_id: 21 },
                { id: 82, nombre: 'Villa Alemana', prov_id: 21 },
                { id: 83, nombre: 'Colina', prov_id: 22 },
                { id: 84, nombre: 'Lampa', prov_id: 22 },
                { id: 85, nombre: 'Tiltil', prov_id: 22 },
                { id: 86, nombre: 'Santiago', prov_id: 23 },
                { id: 87, nombre: 'Vitacura', prov_id: 23 },
                { id: 88, nombre: 'San Ramón', prov_id: 23 },
                { id: 89, nombre: 'San Miguel', prov_id: 23 },
                { id: 90, nombre: 'San Joaquín', prov_id: 23 },
                { id: 91, nombre: 'Renca', prov_id: 23 },
                { id: 92, nombre: 'Recoleta', prov_id: 23 },
                { id: 93, nombre: 'Quinta Normal', prov_id: 23 },
                { id: 94, nombre: 'Quilicura', prov_id: 23 },
                { id: 95, nombre: 'Pudahuel', prov_id: 23 },
                { id: 96, nombre: 'Providencia', prov_id: 23 },
                { id: 97, nombre: 'Peñalolén', prov_id: 23 },
                { id: 98, nombre: 'Pedro Aguirre Cerda', prov_id: 23 },
                { id: 99, nombre: 'Ñuñoa', prov_id: 23 },
                { id: 100, nombre: 'Maipú', prov_id: 23 },
                { id: 101, nombre: 'Macul', prov_id: 23 },
                { id: 102, nombre: 'Lo Prado', prov_id: 23 },
                { id: 103, nombre: 'Lo Espejo', prov_id: 23 },
                { id: 104, nombre: 'Lo Barnechea', prov_id: 23 },
                { id: 105, nombre: 'Las Condes', prov_id: 23 },
                { id: 106, nombre: 'La Reina', prov_id: 23 },
                { id: 107, nombre: 'La Pintana', prov_id: 23 },
                { id: 108, nombre: 'La Granja', prov_id: 23 },
                { id: 109, nombre: 'La Florida', prov_id: 23 },
                { id: 110, nombre: 'La Cisterna', prov_id: 23 },
                { id: 111, nombre: 'Independencia', prov_id: 23 },
                { id: 112, nombre: 'Huechuraba', prov_id: 23 },
                { id: 113, nombre: 'Estación Central', prov_id: 23 },
                { id: 114, nombre: 'El Bosque', prov_id: 23 },
                { id: 115, nombre: 'Conchalí', prov_id: 23 },
                { id: 116, nombre: 'Cerro Navia', prov_id: 23 },
                { id: 117, nombre: 'Cerrillos', prov_id: 23 },
                { id: 118, nombre: 'Puente Alto', prov_id: 24 },
                { id: 119, nombre: 'San José de Maipo', prov_id: 24 },
                { id: 120, nombre: 'Pirque', prov_id: 24 },
                { id: 121, nombre: 'San Bernardo', prov_id: 25 },
                { id: 122, nombre: 'Buin', prov_id: 25 },
                { id: 123, nombre: 'Paine', prov_id: 25 },
                { id: 124, nombre: 'Calera de Tango', prov_id: 25 },
                { id: 125, nombre: 'Melipilla', prov_id: 26 },
                { id: 126, nombre: 'Alhué', prov_id: 26 },
                { id: 127, nombre: 'Curacaví', prov_id: 26 },
                { id: 128, nombre: 'María Pinto', prov_id: 26 },
                { id: 129, nombre: 'San Pedro', prov_id: 26 },
                { id: 130, nombre: 'Isla de Maipo', prov_id: 27 },
                { id: 131, nombre: 'El Monte', prov_id: 27 },
                { id: 132, nombre: 'Padre Hurtado', prov_id: 27 },
                { id: 133, nombre: 'Peñaflor', prov_id: 27 },
                { id: 134, nombre: 'Talagante', prov_id: 27 },
                { id: 135, nombre: 'Codegua', prov_id: 28 },
                { id: 136, nombre: 'Coínco', prov_id: 28 },
                { id: 137, nombre: 'Coltauco', prov_id: 28 },
                { id: 138, nombre: 'Doñihue', prov_id: 28 },
                { id: 139, nombre: 'Graneros', prov_id: 28 },
                { id: 140, nombre: 'Las Cabras', prov_id: 28 },
                { id: 141, nombre: 'Machalí', prov_id: 28 },
                { id: 142, nombre: 'Malloa', prov_id: 28 },
                { id: 143, nombre: 'Mostazal', prov_id: 28 },
                { id: 144, nombre: 'Olivar', prov_id: 28 },
                { id: 145, nombre: 'Peumo', prov_id: 28 },
                { id: 146, nombre: 'Pichidegua', prov_id: 28 },
                { id: 147, nombre: 'Quinta de Tilcoco', prov_id: 28 },
                { id: 148, nombre: 'Rancagua', prov_id: 28 },
                { id: 149, nombre: 'Rengo', prov_id: 28 },
                { id: 150, nombre: 'Requínoa', prov_id: 28 },
                { id: 151, nombre: 'San Vicente de Tagua Tagua', prov_id: 28 },
                { id: 152, nombre: 'Chépica', prov_id: 29 },
                { id: 153, nombre: 'Chimbarongo', prov_id: 29 },
                { id: 154, nombre: 'Lolol', prov_id: 29 },
                { id: 155, nombre: 'Nancagua', prov_id: 29 },
                { id: 156, nombre: 'Palmilla', prov_id: 29 },
                { id: 157, nombre: 'Peralillo', prov_id: 29 },
                { id: 158, nombre: 'Placilla', prov_id: 29 },
                { id: 159, nombre: 'Pumanque', prov_id: 29 },
                { id: 160, nombre: 'San Fernando', prov_id: 29 },
                { id: 161, nombre: 'Santa Cruz', prov_id: 29 },
                { id: 162, nombre: 'La Estrella', prov_id: 30 },
                { id: 163, nombre: 'Litueche', prov_id: 30 },
                { id: 164, nombre: 'Marchigüe', prov_id: 30 },
                { id: 165, nombre: 'Navidad', prov_id: 30 },
                { id: 166, nombre: 'Paredones', prov_id: 30 },
                { id: 167, nombre: 'Pichilemu', prov_id: 30 },
                { id: 168, nombre: 'Curicó', prov_id: 31 },
                { id: 169, nombre: 'Hualañé', prov_id: 31 },
                { id: 170, nombre: 'Licantén', prov_id: 31 },
                { id: 171, nombre: 'Molina', prov_id: 31 },
                { id: 172, nombre: 'Rauco', prov_id: 31 },
                { id: 173, nombre: 'Romeral', prov_id: 31 },
                { id: 174, nombre: 'Sagrada Familia', prov_id: 31 },
                { id: 175, nombre: 'Teno', prov_id: 31 },
                { id: 176, nombre: 'Vichuquén', prov_id: 31 },
                { id: 177, nombre: 'Talca', prov_id: 32 },
                { id: 178, nombre: 'San Clemente', prov_id: 32 },
                { id: 179, nombre: 'Pelarco', prov_id: 32 },
                { id: 180, nombre: 'Pencahue', prov_id: 32 },
                { id: 181, nombre: 'Maule', prov_id: 32 },
                { id: 182, nombre: 'San Rafael', prov_id: 32 },
                { id: 183, nombre: 'Curepto', prov_id: 33 },
                { id: 184, nombre: 'Constitución', prov_id: 32 },
                { id: 185, nombre: 'Empedrado', prov_id: 32 },
                { id: 186, nombre: 'Río Claro', prov_id: 32 },
                { id: 187, nombre: 'Linares', prov_id: 33 },
                { id: 188, nombre: 'San Javier', prov_id: 33 },
                { id: 189, nombre: 'Parral', prov_id: 33 },
                { id: 190, nombre: 'Villa Alegre', prov_id: 33 },
                { id: 191, nombre: 'Longaví', prov_id: 33 },
                { id: 192, nombre: 'Colbún', prov_id: 33 },
                { id: 193, nombre: 'Retiro', prov_id: 33 },
                { id: 194, nombre: 'Yerbas Buenas', prov_id: 33 },
                { id: 195, nombre: 'Cauquenes', prov_id: 34 },
                { id: 196, nombre: 'Chanco', prov_id: 34 },
                { id: 197, nombre: 'Pelluhue', prov_id: 34 },
                { id: 198, nombre: 'Bulnes', prov_id: 35 },
                { id: 199, nombre: 'Chillán', prov_id: 35 },
                { id: 200, nombre: 'Chillán Viejo', prov_id: 35 },
                { id: 201, nombre: 'El Carmen', prov_id: 35 },
                { id: 202, nombre: 'Pemuco', prov_id: 35 },
                { id: 203, nombre: 'Pinto', prov_id: 35 },
                { id: 204, nombre: 'Quillón', prov_id: 35 },
                { id: 205, nombre: 'San Ignacio', prov_id: 35 },
                { id: 206, nombre: 'Yungay', prov_id: 35 },
                { id: 207, nombre: 'Cobquecura', prov_id: 36 },
                { id: 208, nombre: 'Coelemu', prov_id: 36 },
                { id: 209, nombre: 'Ninhue', prov_id: 36 },
                { id: 210, nombre: 'Portezuelo', prov_id: 36 },
                { id: 211, nombre: 'Quirihue', prov_id: 36 },
                { id: 212, nombre: 'Ránquil', prov_id: 36 },
                { id: 213, nombre: 'Treguaco', prov_id: 36 },
                { id: 214, nombre: 'San Carlos', prov_id: 37 },
                { id: 215, nombre: 'Coihueco', prov_id: 37 },
                { id: 216, nombre: 'San Nicolás', prov_id: 37 },
                { id: 217, nombre: 'Ñiquén', prov_id: 37 },
                { id: 218, nombre: 'San Fabián', prov_id: 37 },
                { id: 219, nombre: 'Alto Biobío', prov_id: 38 },
                { id: 220, nombre: 'Antuco', prov_id: 38 },
                { id: 221, nombre: 'Cabrero', prov_id: 38 },
                { id: 222, nombre: 'Laja', prov_id: 38 },
                { id: 223, nombre: 'Los Ángeles', prov_id: 38 },
                { id: 224, nombre: 'Mulchén', prov_id: 38 },
                { id: 225, nombre: 'Nacimiento', prov_id: 38 },
                { id: 226, nombre: 'Negrete', prov_id: 38 },
                { id: 227, nombre: 'Quilaco', prov_id: 38 },
                { id: 228, nombre: 'Quilleco', prov_id: 38 },
                { id: 229, nombre: 'San Rosendo', prov_id: 38 },
                { id: 230, nombre: 'Santa Bárbara', prov_id: 38 },
                { id: 231, nombre: 'Tucapel', prov_id: 38 },
                { id: 232, nombre: 'Yumbel', prov_id: 38 },
                { id: 233, nombre: 'Concepción', prov_id: 39 },
                { id: 234, nombre: 'Coronel', prov_id: 39 },
                { id: 235, nombre: 'Chiguayante', prov_id: 39 },
                { id: 236, nombre: 'Florida', prov_id: 39 },
                { id: 237, nombre: 'Hualpén', prov_id: 39 },
                { id: 238, nombre: 'Hualqui', prov_id: 39 },
                { id: 239, nombre: 'Lota', prov_id: 39 },
                { id: 240, nombre: 'Penco', prov_id: 39 },
                { id: 241, nombre: 'San Pedro de La Paz', prov_id: 39 },
                { id: 242, nombre: 'Santa Juana', prov_id: 39 },
                { id: 243, nombre: 'Talcahuano', prov_id: 39 },
                { id: 244, nombre: 'Tomé', prov_id: 39 },
                { id: 245, nombre: 'Arauco', prov_id: 40 },
                { id: 246, nombre: 'Cañete', prov_id: 40 },
                { id: 247, nombre: 'Contulmo', prov_id: 40 },
                { id: 248, nombre: 'Curanilahue', prov_id: 40 },
                { id: 249, nombre: 'Lebu', prov_id: 40 },
                { id: 250, nombre: 'Los Álamos', prov_id: 40 },
                { id: 251, nombre: 'Tirúa', prov_id: 40 },
                { id: 252, nombre: 'Angol', prov_id: 41 },
                { id: 253, nombre: 'Collipulli', prov_id: 41 },
                { id: 254, nombre: 'Curacautín', prov_id: 41 },
                { id: 255, nombre: 'Ercilla', prov_id: 41 },
                { id: 256, nombre: 'Lonquimay', prov_id: 41 },
                { id: 257, nombre: 'Los Sauces', prov_id: 41 },
                { id: 258, nombre: 'Lumaco', prov_id: 41 },
                { id: 259, nombre: 'Purén', prov_id: 41 },
                { id: 260, nombre: 'Renaico', prov_id: 41 },
                { id: 261, nombre: 'Traiguén', prov_id: 41 },
                { id: 262, nombre: 'Victoria', prov_id: 41 },
                { id: 263, nombre: 'Temuco', prov_id: 42 },
                { id: 264, nombre: 'Carahue', prov_id: 42 },
                { id: 265, nombre: 'Cholchol', prov_id: 42 },
                { id: 266, nombre: 'Cunco', prov_id: 42 },
                { id: 267, nombre: 'Curarrehue', prov_id: 42 },
                { id: 268, nombre: 'Freire', prov_id: 42 },
                { id: 269, nombre: 'Galvarino', prov_id: 42 },
                { id: 270, nombre: 'Gorbea', prov_id: 42 },
                { id: 271, nombre: 'Lautaro', prov_id: 42 },
                { id: 272, nombre: 'Loncoche', prov_id: 42 },
                { id: 273, nombre: 'Melipeuco', prov_id: 42 },
                { id: 274, nombre: 'Nueva Imperial', prov_id: 42 },
                { id: 275, nombre: 'Padre Las Casas', prov_id: 42 },
                { id: 276, nombre: 'Perquenco', prov_id: 42 },
                { id: 277, nombre: 'Pitrufquén', prov_id: 42 },
                { id: 278, nombre: 'Pucón', prov_id: 42 },
                { id: 279, nombre: 'Saavedra', prov_id: 42 },
                { id: 280, nombre: 'Teodoro Schmidt', prov_id: 42 },
                { id: 281, nombre: 'Toltén', prov_id: 42 },
                { id: 282, nombre: 'Vilcún', prov_id: 42 },
                { id: 283, nombre: 'Villarrica', prov_id: 42 },
                { id: 284, nombre: 'Valdivia', prov_id: 43 },
                { id: 285, nombre: 'Corral', prov_id: 43 },
                { id: 286, nombre: 'Lanco', prov_id: 43 },
                { id: 287, nombre: 'Los Lagos', prov_id: 43 },
                { id: 288, nombre: 'Máfil', prov_id: 43 },
                { id: 289, nombre: 'Mariquina', prov_id: 43 },
                { id: 290, nombre: 'Paillaco', prov_id: 43 },
                { id: 291, nombre: 'Panguipulli', prov_id: 43 },
                { id: 292, nombre: 'La Unión', prov_id: 44 },
                { id: 293, nombre: 'Futrono', prov_id: 44 },
                { id: 294, nombre: 'Lago Ranco', prov_id: 44 },
                { id: 295, nombre: 'Río Bueno', prov_id: 44 },
                { id: 297, nombre: 'Osorno', prov_id: 45 },
                { id: 298, nombre: 'Puerto Octay', prov_id: 45 },
                { id: 299, nombre: 'Purranque', prov_id: 45 },
                { id: 300, nombre: 'Puyehue', prov_id: 45 },
                { id: 301, nombre: 'Río Negro', prov_id: 45 },
                { id: 302, nombre: 'San Juan de la Costa', prov_id: 45 },
                { id: 303, nombre: 'San Pablo', prov_id: 45 },
                { id: 304, nombre: 'Calbuco', prov_id: 46 },
                { id: 305, nombre: 'Cochamó', prov_id: 46 },
                { id: 306, nombre: 'Fresia', prov_id: 46 },
                { id: 307, nombre: 'Frutillar', prov_id: 46 },
                { id: 308, nombre: 'Llanquihue', prov_id: 46 },
                { id: 309, nombre: 'Los Muermos', prov_id: 46 },
                { id: 310, nombre: 'Maullín', prov_id: 46 },
                { id: 311, nombre: 'Puerto Montt', prov_id: 46 },
                { id: 312, nombre: 'Puerto Varas', prov_id: 46 },
                { id: 313, nombre: 'Ancud', prov_id: 47 },
                { id: 314, nombre: 'Castro', prov_id: 47 },
                { id: 315, nombre: 'Chonchi', prov_id: 47 },
                { id: 316, nombre: 'Curaco de Vélez', prov_id: 47 },
                { id: 317, nombre: 'Dalcahue', prov_id: 47 },
                { id: 318, nombre: 'Puqueldón', prov_id: 47 },
                { id: 319, nombre: 'Queilén', prov_id: 47 },
                { id: 320, nombre: 'Quellón', prov_id: 47 },
                { id: 321, nombre: 'Quemchi', prov_id: 47 },
                { id: 322, nombre: 'Quinchao', prov_id: 47 },
                { id: 323, nombre: 'Chaitén', prov_id: 48 },
                { id: 324, nombre: 'Futaleufú', prov_id: 48 },
                { id: 325, nombre: 'Hualaihué', prov_id: 48 },
                { id: 326, nombre: 'Palena', prov_id: 48 },
                { id: 327, nombre: 'Lago Verde', prov_id: 49 },
                { id: 328, nombre: 'Coihaique', prov_id: 49 },
                { id: 329, nombre: 'Aysén', prov_id: 50 },
                { id: 330, nombre: 'Cisnes', prov_id: 50 },
                { id: 331, nombre: 'Guaitecas', prov_id: 50 },
                { id: 332, nombre: 'Río Ibáñez', prov_id: 51 },
                { id: 333, nombre: 'Chile Chico', prov_id: 51 },
                { id: 334, nombre: 'Cochrane', prov_id: 52 },
                { id: 335, nombre: 'O\'Higgins', prov_id: 52 },
                { id: 336, nombre: 'Tortel', prov_id: 52 },
                { id: 337, nombre: 'Natales', prov_id: 53 },
                { id: 338, nombre: 'Torres del Paine', prov_id: 53 },
                { id: 339, nombre: 'Laguna Blanca', prov_id: 54 },
                { id: 340, nombre: 'Punta Arenas', prov_id: 54 },
                { id: 341, nombre: 'Río Verde', prov_id: 54 },
                { id: 342, nombre: 'San Gregorio', prov_id: 54 },
                { id: 343, nombre: 'Porvenir', prov_id: 55 },
                { id: 344, nombre: 'Primavera', prov_id: 55 },
                { id: 345, nombre: 'Timaukel', prov_id: 55 },
                { id: 346, nombre: 'Cabo de Hornos', prov_id: 56 },
                { id: 347, nombre: 'Antártica', prov_id: 56 }
              ]
)

puts 'Creando Patrimonio tipo ...'

PatrimonioTipo.create(
  [
    { id: 1, nombre: 'Patrimonio Inmaterial: Tesoro Humano Vivo', active: true },
    { id: 2, nombre: 'Patrimonio Inmaterial: Festividades', active: true },
    { id: 3, nombre: 'Arquitectónico', active: true },

  ]
)
puts "Creando usuario id:1 test1@gmail.com ..."
User.create(
  id: 1,
  email: "test1@gmail.com",
  nombre: "111111111",
  apellidos: "111111111111",
  tipo_usuario: 0,
  password:              "123456",
  password_confirmation: "123456"
)
puts "Creando usuario id:2 test2@gmail.com ..."

User.create(
  id: 2,
  email: "test2@gmail.com",
  nombre: "2222222222222",
  apellidos: "222222222",
  tipo_usuario: 0,
  password:              "123456",
  password_confirmation: "123456"
)
puts "Creando usuario id:3 test3@gmail.com ..."
User.create(
  id: 3,
  email: "test3@gmail.com",
  nombre: "Americo",
  apellidos: "Muller",
  tipo_usuario: 0,
  password:              "123456",
  password_confirmation: "123456"
)

puts "Creando usuario id:4 test4@gmail.com ..."
User.create(
  id: 4,
  email: "test4@gmail.com",
  nombre: "33333333333",
  apellidos: "33333",
  tipo_usuario: 0,
  password: "123456",
  password_confirmation: "123456"
)

puts 'OK Seed completado.'
